config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'

  # As a user I can see one garden's plants
  resources :gardens, only: [:show, :index] do
    # As a user I can add a plant in a garden
    # POST gardens/:id/plants
    resources :plants, only: [:create]
  end

  # As a user I can delete a plant
  resources :plants, only: [:destroy] do
    resources :plant_tags, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy

  validates :name, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags

  validates :name, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag

  validates :tag, uniqueness: { scope: :plant, message: "already taken" }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags, dependent: :destroy
  has_many :plants, through: :plant_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])

    @plant = Plant.new
  end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant_tag = PlantTag.new
    @plant = Plant.find(params[:plant_id])
    @tags = Tag.where.not(id: @plant.tags)
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new(plant_tag_params)
    @plant_tag.plant = @plant
    if @plant_tag.save
      redirect_to garden_path(@plant.garden)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def plant_tag_params
    params.require(:plant_tag).permit(:tag_id)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @plant = Plant.new(plant_params)

    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden

    if @plant.save
      redirect_to garden_path(@garden)
    else
      render "gardens/show", status: :unprocessable_entity
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_garden.html.erb
<div class="card-category position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= garden.banner_url %>')">
  <%= garden.name %>

  <%= link_to garden_path(garden),
    class: "card-top-icon-link regular-link position-absolute top-0 start-100 rounded-circle translate-middle" do %>
    <i class="fa-solid fa-eye fa-xs"></i>
  <% end %>
</div>

app/views/gardens/index.html.erb
<div class="container text-center mt-4">
  <h1>Our Gardens</h1>

  <ul class="list-unstyled row row-cols-12 gap-2">
    <% @gardens.each do |garden| %>
      <li class="col-12 col-sm-6 col-md-4">
        <%= render 'gardens/garden', garden: garden %>
      </li>
    <% end %>
  </ul>
</div>

app/views/gardens/show.html.erb
<div class="banner d-flex px-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>

  <div class="container bg-light p-4 rounded-2 shadow-sm w-50 mx-auto">
    <h4>Add a plant to this garden</h4>
    <%= simple_form_for [@garden, @plant] do |f| %>
      <%= f.input :name %>
      <%= f.input :picture_url %>

      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>

</div>

<div class="container text-center mt-4">
  <ul class="list-unstyled row row-cols-12 gap-2">
    <% @garden.plants.each do |plant| %>
      <li class="col-12 col-sm-6 col-md-4">
        <%= render 'plants/plant', plant: plant %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-black text-white p-4 mt-auto d-flex justify-content-between">
  <span>
    Made with love for Le Wagon Tokyo Batch 1383
  </span>
  <span>❤️</span>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container mt-3">
  <h1>Add a tag to the plant</h1>
  <%= simple_form_for([@plant, @plant_tag]) do |f| %>
    <%= f.association :tag, collection: @tags %>
    <%= f.submit "Add", class: "btn btn-primary" %> 
  <% end %>
</div>

app/views/plants/_plant.html.erb
<div class="card-category position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.picture_url %>')">
  <%= plant.name %>

  <%= link_to plant_path(plant),
    class: "card-top-icon-link danger-link position-absolute top-0 start-100 rounded-circle translate-middle" ,
    data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure you want to delete this plant?"
    } do %>
    <i class="fa-solid fa-trash fa-xs"></i>
  <% end %>

  <div class="card-tags">
    <% plant.tags.each do |tag| %>
      <span><%= tag.name %></span>
    <% end %>
  </div>
  <%= link_to '+', new_plant_plant_tag_path(plant), class: "plus-link" %>
</div>